### PR TITLE
Update README.md with badges to show all pipeline statuses.

### PR DESCRIPTION
**Pull request by mohammedri**
Update README.md with badges to show all pipeline statuses.

### CODE REVIEW

**Comment by mohammedri** [comment]
Github Actions is failing due to: 
```
ImportError: cannot import name 'Context' from 'docker' (/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/site-packages/docker/__init__.py)```

**Comment by amackillop** [comment]
> Github Actions is failing due to:
> 
> ```
> ImportError: cannot import name 'Context' from 'docker' (/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/site-packages/docker/__init__.py)```
> ```

Investigating

**Comment by amackillop** [comment]
Tried things out locally and everything works as expected. The only difference is that the pipeline installs docker-compose via python while I use my system install. The problem is that `docker-compose` [released](https://pypi.org/project/docker-compose/) 7 hours ago and is probably no longer compatible with our pinned `docker` requirement. We can pin `docker-compose` to the last version (1.25.5) and that should fix it.

**Comment by amackillop** [comment]
I verified that installing the latest docker-compose causes the fail to happen locally while installing version 1.25.5 succeeds.

**Comment by mohammedri** [comment]
Thanks @amackillop !

**Pull request merged**
