### PR TITLE
Let's add github actions

### PR DESCRIPTION
**Pull request by amackillop**
This is a basic template for adding a github actions pipeline. Will always pass.

### CODE REVIEW

**Comment by amackillop** [comment]
Certainly! Unit testing should just work.

**Comment by amackillop** [comment]
Unit tests are passing :tada:

**Comment by amackillop** [comment]
Passing for all Python versions 3.6+

**Comment by mohammedri** [comment]
Related: https://github.com/dessa-oss/atlas/issues/21

**Comment by kyledef** [comment]
> Related: #21

While I think its related, I feel that the #21 ticket is related to the overall move from Jenkins to Github. With the need to think about upgrading the k8s cluster, there is a greater need to move to github actions.

**Pull request merged**
